### ISSUE TITLE
User can search through numerous Pokémon

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#1]
## ⚙️ Feature

> ##### User can search through numerous Pokémon. 

## 📐 Functionality

> ##### When the user types  the correct name in the search bar the corresponding Pokémon shows up in the result.

## 🖼️ Wireframes

> ##### mobile / desktop

![image](https://user-images.githubusercontent.com/121650766/222008486-303f1d51-bf46-4590-97db-7d3d5b44fd49.png)
![image](https://user-images.githubusercontent.com/121650766/222008539-dc6f55a7-6830-4039-875c-d021df887d0a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Begin the html skeleton. 
- [x] Create a nav bar that stays in the same 
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Have view changes between the search and party buttons
- [x] On search bar view create a function that pulls from the API and stores data in the local storage. 
- [x] Create a search function to look through the local storage to find the appropriate Pokémon. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
