### ISSUE TITLE
Design Update: 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#12]
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Open the [User Interfaces](https://github.com/Learning-Fuze/lfz-portfolios/tree/master/project-interfaces) guide for reference.
- [x] Make all buttons and icons show the correct cursor.
- [x] Ensure that the user interface fluidly adapts (**mobile-first**) to:
  - [x] smartphones
  - [x] tablets
  - [x] laptops and desktops
- [x] Ensure that the user interface passes **The Wiggle Test ™️**.
- [x] Remove all "placeholders": links, buttons, and inputs that don't do anything yet.
- [x] Effectively communicate network activity and data fetching results to the user when:
  - [x] data is loading
  - [x] results are empty
  - [x] a connection error occurs
- [x] Send a link to my AJAX Project website to portfolio reviewer / instructor.
