### ISSUE TITLE
User can add Pokémon to their party 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#2]
## ⚙️ Feature

User can add Pokémon to their party 

## 📐 Functionality

When user clicks the plus button the Pokémon's data is stored in local storage and eventually added to the party tab.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121650766/222010809-e6df16c7-ade9-4c5d-9a1b-2c1d12bfabc0.png)
![image](https://user-images.githubusercontent.com/121650766/222010852-048b7022-c9a1-449a-8435-e6e9c9bc989b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a plus button in html
  - [x] add the button to the Pokémon object and hide its view when the Pokémon is not showing
- [x] Test the data to make sure it is showing up after the add button is clicked
- [x] Add a HTML and CSS to match wire frame of the Pokémon retrieval 
- [x] Make sure the Pokémon is removed when there is no input in the search engine
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
