### ISSUE TITLE
User can view Pokémon in their party 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#3]
## ⚙️ Feature

User can view Pokémon in their party

## 📐 Functionality

New view created to check the Pokémon in the party. any time the plus button is pressed it automatically adds the Pokémon to the party. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121650766/222052360-405f109c-b495-4cb3-a53b-24b8b84c6698.png)
![image](https://user-images.githubusercontent.com/121650766/222052309-315f315c-e884-47ab-975c-eb86b9cf3f89.png)

## ✅ Task List

- [x] Create a new view for the party tab
  - [x] Develop the HTML and CSS for the new view
- [x] Link the button "party" with the view so the view can be swapped back and forth.
- [x] Use data from local storage and add it to the view when the new Pokémon is added 
  - [x] Make sure every thing is aligned properly before moving on to JavaScript
  - [x] Make sure the correct local storage goes to the correct location. 
  - [x] Use DOM Tree to create every new party member
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
