### ISSUE TITLE
User can remove pokemon from their party 

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#4]
## ⚙️ Feature

User can remove Pokémon from their party 

## 📐 Functionality

When the minus button  is clicked a modal appears to determine if the current party member should be removed. 
When none are visible a message is viewed only when empty. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121650766/222054304-9930eaec-70fc-4d07-b9dd-8064f515f874.png)
![image](https://user-images.githubusercontent.com/121650766/222054339-73cc65ea-4265-4d31-ba7c-25728ebc878f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create new minus button attached to each new object
- [x] Create new modal hidden in the back ground
  - [x] create a function that removes the current clicked party member
- [x] when new button is pressed have modal pop up 
  - [x] Have two buttons appear on modal to either cancel modal or remove the new member
  - [x] When remove button is pressed remove from view and local data 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
