### ISSUE TITLE
User can switch between shiny and non shiny sprite images with a button click

### ISSUE THREAD

**Issue by Nathan-Chon** [Nathan-Chon/ajax-project#5]
## ⚙️ Feature

User can switch between shiny and non shiny sprite images with a button click

## 📐 Functionality

When the star is clicked the Pokémon is changed to have a shiny sprite instead of the usual colors. 

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121650766/222056749-c20ba364-8a6c-4e93-ae03-b9639667cf22.png)
![image](https://user-images.githubusercontent.com/121650766/222056813-609b6fce-b028-4115-a7ec-5e591fe04ce6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a shiny star to every new member of the party 
- [x] Make shiny star a button to press and be highlighted when pressed
- [x] When pressed the sprite updates immediately and on local storage
  - [x] Make sure sprite changes when viewed and refreshed. 
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
